# Generated by Django 4.2.5 on 2023-09-19 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0003_remove_customuser_user_id_alter_customuser_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default=True, max_length=100, unique=True),
        ),
    ]
