# Generated by Django 4.2.5 on 2023-09-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0005_alter_customuser_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=30, null=True)),
                ("product_price", models.IntegerField(null=True)),
                ("product_description", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
