# Generated by Django 4.2.5 on 2023-09-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0006_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="phone_num",
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
