# Generated by Django 4.2.5 on 2023-09-20 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0010_custompermission"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customgroup",
            old_name="names",
            new_name="department",
        ),
    ]
