# Generated by Django 4.2.5 on 2023-09-20 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0011_rename_names_customgroup_department"),
    ]

    operations = [
        migrations.RenameField(
            model_name="custompermission",
            old_name="codenames",
            new_name="description",
        ),
        migrations.RemoveField(
            model_name="custompermission",
            name="names",
        ),
        migrations.AddField(
            model_name="custompermission",
            name="category",
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name="custompermission",
            name="resource",
            field=models.ForeignKey(
                default=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
