# Generated by Django 4.2.5 on 2023-09-20 07:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task_app", "0012_rename_codenames_custompermission_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="custompermission",
            name="resource",
        ),
    ]
